.travis.yml:
  env:
    global:
      - ORG_PATH=/home/travis/gopath/src/github.com/intelsdi-x
      - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/${TRAVIS_REPO_SLUG}
    # NOTE: PCM test matrix is disabled because pcm.x is not supported in travis.
    # see following travis test for more information:
    # https://travis-ci.org/intelsdi-x/snap-plugin-collector-pcm/jobs/161792384#L165-L192
    # matrix:
